/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'sectionDescription' : string,
  'featureCards' : Array<FeatureCard>,
}
export interface ContactContent {
  'email' : string,
  'website' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
}
export interface Coordinator {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export interface CoordinatorsContent {
  'studentCoordinators' : Array<Coordinator>,
  'facultyCoordinators' : Array<Coordinator>,
}
export interface EventDetailsContent {
  'venue' : string,
  'timelineMilestones' : Array<TimelineMilestone>,
  'projectCategories' : Array<string>,
  'eligibilityCriteria' : string,
  'registrationFee' : string,
  'eventDate' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeatureCard {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'imageBlob' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface HeroContent {
  'tagline' : string,
  'collegeName' : string,
  'eventTitle' : string,
  'eventDate' : string,
}
export interface Registration {
  'id' : bigint,
  'collegeName' : string,
  'fullName' : string,
  'email' : string,
  'projectTitle' : string,
  'timestamp' : bigint,
  'abstract' : string,
  'category' : string,
  'department' : string,
  'phoneNumber' : string,
}
export interface TimelineMilestone {
  'milestoneLabel' : string,
  'date' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[string, ExternalBlob], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], boolean>,
  'deleteRegistration' : ActorMethod<[bigint], boolean>,
  'getAboutContent' : ActorMethod<[], [] | [AboutContent]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactContent' : ActorMethod<[], [] | [ContactContent]>,
  'getCoordinatorsContent' : ActorMethod<[], [] | [CoordinatorsContent]>,
  'getEventDetailsContent' : ActorMethod<[], [] | [EventDetailsContent]>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHeroContent' : ActorMethod<[], [] | [HeroContent]>,
  'getRegistrationByEmail' : ActorMethod<[string], [] | [Registration]>,
  'getRegistrationCount' : ActorMethod<[], bigint>,
  'getRegistrations' : ActorMethod<[], Array<Registration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRegistration' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    bigint
  >,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateContactContent' : ActorMethod<[ContactContent], undefined>,
  'updateCoordinatorsContent' : ActorMethod<[CoordinatorsContent], undefined>,
  'updateEventDetailsContent' : ActorMethod<[EventDetailsContent], undefined>,
  'updateHeroContent' : ActorMethod<[HeroContent], undefined>,
  'updateRegistration' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];