/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeatureCard = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const AboutContent = IDL.Record({
  'sectionDescription' : IDL.Text,
  'featureCards' : IDL.Vec(FeatureCard),
});
export const RegistrationRecord = IDL.Record({
  'id' : IDL.Nat,
  'collegeName' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'projectTitle' : IDL.Text,
  'timestamp' : IDL.Int,
  'abstract' : IDL.Text,
  'category' : IDL.Text,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ContactContent = IDL.Record({
  'email' : IDL.Text,
  'website' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
});
export const Coordinator = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CoordinatorsContent = IDL.Record({
  'studentCoordinators' : IDL.Vec(Coordinator),
  'facultyCoordinators' : IDL.Vec(Coordinator),
});
export const TimelineMilestone = IDL.Record({
  'milestoneLabel' : IDL.Text,
  'date' : IDL.Text,
});
export const EventDetailsContent = IDL.Record({
  'venue' : IDL.Text,
  'timelineMilestones' : IDL.Vec(TimelineMilestone),
  'projectCategories' : IDL.Vec(IDL.Text),
  'eligibilityCriteria' : IDL.Text,
  'registrationFee' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const HeroContent = IDL.Record({
  'tagline' : IDL.Text,
  'collegeName' : IDL.Text,
  'eventTitle' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'collegeName' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'projectTitle' : IDL.Text,
  'timestamp' : IDL.Int,
  'abstract' : IDL.Text,
  'category' : IDL.Text,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
  'getAdminHostEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getAllRegistrationRecords' : IDL.Func(
      [],
      [IDL.Vec(RegistrationRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactContent' : IDL.Func([], [IDL.Opt(ContactContent)], ['query']),
  'getCoordinatorsContent' : IDL.Func(
      [],
      [IDL.Opt(CoordinatorsContent)],
      ['query'],
    ),
  'getEventDetailsContent' : IDL.Func(
      [],
      [IDL.Opt(EventDetailsContent)],
      ['query'],
    ),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
  'getRegistrationByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Registration)],
      ['query'],
    ),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateAboutContent' : IDL.Func([AboutContent], [], []),
  'updateContactContent' : IDL.Func([ContactContent], [], []),
  'updateCoordinatorsContent' : IDL.Func([CoordinatorsContent], [], []),
  'updateEventDetailsContent' : IDL.Func([EventDetailsContent], [], []),
  'updateHeroContent' : IDL.Func([HeroContent], [], []),
  'updateRegistration' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeatureCard = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const AboutContent = IDL.Record({
    'sectionDescription' : IDL.Text,
    'featureCards' : IDL.Vec(FeatureCard),
  });
  const RegistrationRecord = IDL.Record({
    'id' : IDL.Nat,
    'collegeName' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'projectTitle' : IDL.Text,
    'timestamp' : IDL.Int,
    'abstract' : IDL.Text,
    'category' : IDL.Text,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ContactContent = IDL.Record({
    'email' : IDL.Text,
    'website' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Coordinator = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CoordinatorsContent = IDL.Record({
    'studentCoordinators' : IDL.Vec(Coordinator),
    'facultyCoordinators' : IDL.Vec(Coordinator),
  });
  const TimelineMilestone = IDL.Record({
    'milestoneLabel' : IDL.Text,
    'date' : IDL.Text,
  });
  const EventDetailsContent = IDL.Record({
    'venue' : IDL.Text,
    'timelineMilestones' : IDL.Vec(TimelineMilestone),
    'projectCategories' : IDL.Vec(IDL.Text),
    'eligibilityCriteria' : IDL.Text,
    'registrationFee' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const HeroContent = IDL.Record({
    'tagline' : IDL.Text,
    'collegeName' : IDL.Text,
    'eventTitle' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'collegeName' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'projectTitle' : IDL.Text,
    'timestamp' : IDL.Int,
    'abstract' : IDL.Text,
    'category' : IDL.Text,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
    'getAdminHostEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getAllRegistrationRecords' : IDL.Func(
        [],
        [IDL.Vec(RegistrationRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactContent' : IDL.Func([], [IDL.Opt(ContactContent)], ['query']),
    'getCoordinatorsContent' : IDL.Func(
        [],
        [IDL.Opt(CoordinatorsContent)],
        ['query'],
      ),
    'getEventDetailsContent' : IDL.Func(
        [],
        [IDL.Opt(EventDetailsContent)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getHeroContent' : IDL.Func([], [IDL.Opt(HeroContent)], ['query']),
    'getRegistrationByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateAboutContent' : IDL.Func([AboutContent], [], []),
    'updateContactContent' : IDL.Func([ContactContent], [], []),
    'updateCoordinatorsContent' : IDL.Func([CoordinatorsContent], [], []),
    'updateEventDetailsContent' : IDL.Func([EventDetailsContent], [], []),
    'updateHeroContent' : IDL.Func([HeroContent], [], []),
    'updateRegistration' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };